AWSTemplateFormatVersion: '2010-09-09'
Description: Name Tags will be automatically filled. 

    
Resources:

    VPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: "10.0.0.0/16"

    SubnetPublic1:
      Type: "AWS::EC2::Subnet"
      Properties:
        AvailabilityZone : "eu-west-1a"
        CidrBlock: "10.0.1.0/24"
        MapPublicIpOnLaunch: True
        VpcId:
          Ref: VPC


    SubnetPublic2:
      Type: "AWS::EC2::Subnet"
      Properties:
        AvailabilityZone : "eu-west-1b"
        CidrBlock: "10.0.3.0/24"
        MapPublicIpOnLaunch: True
        VpcId:
          Ref: VPC


    SubnetPrivate1:
      Type: "AWS::EC2::Subnet"
      Properties:
        AvailabilityZone : "eu-west-1a"
        CidrBlock: "10.0.2.0/24"
        MapPublicIpOnLaunch: True
        VpcId:
          Ref: VPC

    SubnetPrivate2:
      Type: "AWS::EC2::Subnet"
      Properties:
        AvailabilityZone : "eu-west-1b"
        CidrBlock: "10.0.4.0/24"
        MapPublicIpOnLaunch: True
        VpcId:
          Ref: VPC


    InternetGateway:
        Type: AWS::EC2::InternetGateway


    InternetGatewayAttachment:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
            InternetGatewayId: !Ref InternetGateway
            VpcId: !Ref VPC

    PublicRouteTable:
        Type: AWS::EC2::RouteTable
        Properties:
            VpcId: !Ref VPC


    DefaultPublicRoute:
        Type: AWS::EC2::Route
        DependsOn: InternetGatewayAttachment
        Properties:
            RouteTableId: !Ref PublicRouteTable
            DestinationCidrBlock: 0.0.0.0/0
            GatewayId: !Ref InternetGateway

    PublicSubnet1RouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId: !Ref PublicRouteTable
            SubnetId: !Ref SubnetPublic1

    PublicSubnet2RouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId: !Ref PublicRouteTable
            SubnetId: !Ref SubnetPublic2


Outputs:
    VpcId: 
        Value: !Ref VPC
    PublicSubnet1:
        Value: !Ref SubnetPublic1     
    PublicSubnet2:
        Value: !Ref SubnetPublic2
    PrivateSubnet1:
        Value: !Ref SubnetPrivate1
    PrivateSubnet2:
        Value: !Ref SubnetPrivate2
        
Transform:
  - TaggerMakro