AWSTemplateFormatVersion: '2010-09-09'
Description: 'Root Template'
Resources:

    NetworkResources:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3-eu-west-1.amazonaws.com/testbucket123123123123123/BasicNetowork.yaml
            
    LinuxServer:
        Type: AWS::EC2::Instance
        Properties: 
            ImageId: ami-9398d3e0
            SubnetId: !GetAtt NetworkResources.Outputs.PublicSubnet1
 
 
Outputs:
    ServerID: 
        Value: !Ref LinuxServer
    PrivateIP:
        Value: !GetAtt LinuxServer.PrivateIp
    PublicIP:
        Value: !GetAtt LinuxServer.PublicIp    
    