AWSTemplateFormatVersion: '2010-09-09'
Description: 'Secret Manager Template'


Resources:


    MySecret1:
        Type: AWS::SecretsManager::Secret
        Properties:
            Name: MY_SECRET_1
            Description: 'My First Secret'
            SecretString: "254132524314524313423141412341324"

    MySecret2:
        Type: AWS::SecretsManager::Secret
        Properties:
            Name: MY_SECRET_2
            Description: 'My First Secret'
            GenerateSecretString:
                SecretStringTemplate: '{"username": "admin"}'
                GenerateStringKey: 'password'
                PasswordLength: 16
                ExcludeCharacters: '"@/\'

    MyParam1:
        Type: AWS::SSM::Parameter
        Properties:
          Description: My IP Address
          Name: MY_IP
          Type: String
          Value: 8.8.8.8

    MyParam2:
        Type: AWS::SSM::Parameter
        Properties:
          Description: My HOSTNAME
          Name: MY_HOSTNAME
          Type: String
          Value: mycompany.org
