AWSTemplateFormatVersion: "2010-09-09"

Resources:

  SimplyLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: "lambda.handler"
      Role: !GetAtt SimplyLambdaRole.Arn
      Code:
        S3Bucket: "cloudbuildersday"
        S3Key: "lab-other/simplelambda.zip"
      Runtime: "python3.7"
      MemorySize: 128
      Timeout: 600
      Environment:
        Variables:
          PARAM_1: '{{resolve:ssm:MY_IP:1}}'
          PARAM_2: '{{resolve:ssm:MY_HOSTNAME:1}}'
          SECRET_1: '{{resolve:secretsmanager:MY_SECRET_1}}'
          SECRET_2_USERNAME: '{{resolve:secretsmanager:MY_SECRET_2:SecretString:username}}'
          SECRET_2_PASSPRD: '{{resolve:secretsmanager:MY_SECRET_2:SecretString:password}}'
          
          

  SimplyLambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: AdministratorAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"
       
