<html>
  <head>
    <title>AWS LINUX SERVER</title>
  </head>
  <body>

    <BR>

      <CENTER>
        <img src="logo.jpg" valign="center" width="200">
      </CENTER>


    <BR><BR><BR>
      <CENTER>
    <B> This is webpage on server, generated by Beanstalk</B>
      </CENTER>

    <BR><BR><BR>

      <CENTER>
        <table style="width:40%">
      <tr>
        <td><B>Instance ID</B></td>
        <td>
          <?php
            $instanceId = file_get_contents('http://169.254.169.254/latest/meta-data/instance-id');
            echo "{$instanceId}";
          ?>
        </td>
      </tr>
      <tr>
        <td><B>Current Time</B>
        </td>
        <td><?php echo "Current time is " . date("h:i:sa"); ?><br/><br/></td>
      </tr>
      <tr>
        <td bgcolor=<?php echo substr($instanceId,4) ?>><br/><br/><br/><br/><br/></td>
        <td bgcolor=<?php echo substr($instanceId,4) ?>><br/><br/><br/><br/><br/></td>
      </tr>
    </table>
  </CENTER>


 </body>
</html>